spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kafka-demo}
    username: user
    password: admin
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    defer-datasource-initialization: true
server:
  port: 8087
  error:
    include-message: always
